version: '3'
services:
  blockchain:
    image: trufflesuite/ganache-cli:latest
    ports:
      - ${RPC_PORT:-8545}:8545
    container_name: sanicrap-blkchain
  sanicrap:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanicrap:dev
    container_name: sanicrap
    command: python main.py --debug 0.0.0.0 80
    environment:
      APP_NAME: 'proxy'
      ADMIN_URL: 'http://172.17.0.1:8000'
      NODE_URL: 'http://blockchain:8545'
    ports:
    - 80:80
    volumes:
    - .:/opt/project
