version: '3'
services:
  db:
    image: postgres:12.0-alpine
    restart: always
    container_name: sanicrap-postgres
    expose:
      - 5432
  sanicrap:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanicrap:dev
    container_name: sanicrap
    command: python main.py
